# Generated by Django 3.2.8 on 2021-10-29 21:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('priority', models.CharField(choices=[('high', 'high'), ('med', 'med'), ('low', 'low')], default='low', max_length=20)),
                ('status', models.CharField(choices=[('in_progress', 'in_progress'), ('unstarted', 'unstarted'), ('finished', 'finished')], default='unstarted', max_length=20)),
                ('estimated_time', models.TimeField()),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project_manager.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeatureRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('unreviewed', 'unreviewed'), ('in_progress', 'in_progress'), ('finished', 'finished'), ('denied', 'denied')], default='unreviewed', max_length=20)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project_manager.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BugReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project_manager.project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
