# Generated by Django 3.2.8 on 2021-11-07 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='estimated_time',
        ),
        migrations.AddField(
            model_name='bugreport',
            name='details',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='featurerequest',
            name='details',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='details',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='version',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
